version: '3'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/etc/ssl/certs
